### ISSUE TITLE
ORCM aggregator does not writte monitoring data into the DB at all for some nodes

### ISSUE THREAD

**Issue by forzaclaudio** [open-mpi/orcm#145]
This issue was observed when the aggregator was running under heavy network traffic conditions. Network traffic was mainly due to the 32 compute nodes writing to an NFS file system being hosted on the same aggregator.

![headnodeorcmdb-sigardiskiottotal](https://cloud.githubusercontent.com/assets/8369713/5865193/3582db50-a24d-11e4-84c9-f60373d7bd48.png)
**Figure 1.** Data written into the DB during ORCM execution (aggregator daemon) for 10 minutes. Metric analyzed is the total amount of IO time spent when writting to disk. The amount of data missing for this node, is approximately 8 mins worth of monitoring data. This has been already filed under issue #90 

![node02orcmdb-sigardiskiottotal](https://cloud.githubusercontent.com/assets/8369713/5865214/663bac18-a24d-11e4-90ab-66990aa0d64f.png)
**Figure 2.** Data written into the DB during ORCM execution (compute daemon) for 10 minutes. Metric analyzed is the total amount of IO time spent when writting to disk. The amount of data missing for this node, is aproximately 9.5 mins worth of monitoring data for this node. This has been already filed under issue #90 

![node03orcmdb-sigardiskiottotal](https://cloud.githubusercontent.com/assets/8369713/5865300/00ea3554-a24e-11e4-9155-0872cde9d589.png)
**Figure 2.** Data written into the DB during ORCM execution (compute daemon) for 10 minutes. Metric analyzed is the total amount of IO time spent when writting to disk. The amount of data missing for this node, is the **total of the monitoring time**. 

The following table summarizes the nodes whose data is missing from the DB. Is very likely that the nodes missing for this runs, won't be the same in other runs

Node  | missing data in DB |
--------|--------------------------------|
headnode | no |
node01 | **yes** |
node02 | no |
node03 | **yes** |
node04 | **yes** |
node05 | **yes** |
node06 | no |
node07 | **yes** |
node08 | no |
node09 | no |
node10 | no |
node11 | **yes** |
node12 | **yes** |
node13 | **yes** |
node14 | **yes** |
node15 | **yes** |
node16 | no |
node17 | no |
node18 | no |
node19 | no |
node20 | no |
node21 | no |
node22 | no |
node23 | **yes** |
node24 | no |
node25 | no |
node26 | **yes** |
node27 | no |
node28 | no |
node29 | no |
node30 | **yes** |
node31 | **yes** |
node32 | no |

**Comment by avilcheslopez** [comment]
Fix for issue #104 should help fix this issue.  Fix pushed into master and release branch.

**Comment by forzaclaudio** [comment]
Had the chance to repeat this test with only the FREQUENCY component and the issue seems to be alleviated. We can't declare it as fixed until we specifically test the SIGAR component. Nonetheless, in a 32-node system, looks like this time none of the nodes were left out by aggregator when writing monitoring data to the DB. On the other hand, perfomance took a serious hit. The amount of data sucessfully written into the DB for a period of 10 minutes was between 15 and 20 seconds as shown below:

![headnodeorcmdb-frequency](https://cloud.githubusercontent.com/assets/8369713/5963976/3d04805e-a7b6-11e4-8046-15c71189e555.png)
**Figure 1** Amount of data written by ORCM aggregator to the DB during a 10-minute monitoring interval under heavy network traffic conditions. Data logged corresponds to the aggregator node's frequencies sampled at a 5-sec rate.

![node01orcmdb-frequency](https://cloud.githubusercontent.com/assets/8369713/5963985/4e1ab87c-a7b6-11e4-8683-df456d274fab.png)
**Figure 2** Amount of data written by ORCM aggregator to the DB during a 10-minute monitoring interval under heavy network traffic conditions. Data logged corresponds to the indicated compute node's frequencies sampled at a 5-sec rate.

![node32orcmdb-frequency](https://cloud.githubusercontent.com/assets/8369713/5963989/538b03d4-a7b6-11e4-8c8e-4cf90538a11d.png)
**Figure 3** Amount of data written by ORCM aggregator to the DB during a 10-minute monitoring interval under heavy network traffic conditions. Data logged corresponds to the indicated compute node's frequencies sampled at a 5-sec rate.

**Comment by forzaclaudio** [comment]
We ran this test with ORCM to log only the SIGAR component but unfortunately this issue is still present. Not only the amount of data written into the DB is much less than in the case of the FREQUENCY component but also data from some nodes is missing altogether. I think the SIGAR component is struggling more than the FREQUENCY component. This is most likely due to the fact SIGAR is interacting with the filesystem and network i.e. NFS filesystem, and both are heavily stressed.

![headnodeorcmdb-sigardiskiottotal](https://cloud.githubusercontent.com/assets/8369713/5980905/be0d2a4c-a87a-11e4-818f-4afc5c848f4c.png)
**Figure 1.** Amount of SIGAR component data successfully logged into the DB for a 10-minute monitoring interval at an aggregator node. Network speed is 1000 Mb/s

![node01orcmdb-sigardiskiottotal](https://cloud.githubusercontent.com/assets/8369713/5980945/2d179dd2-a87b-11e4-8ebd-ca1c05df7298.png)
**Figure 2.** Amount of SIGAR component data successfully logged into the DB for a 10-minute monitoring interval at a compute node. Network speed is 1000 Mb/s

The following table summarizes the nodes whose data were not written to the DB during a run using the separate event base fix. In this case, missing data only indicates that no data was written into the DB at all, although the writing lag is comparable with the actual interval of monitoring.

Node  |	missing data in DB
---------|---------------------------
headnode |	no
node01	|no
node02	|no
node03	|no
node04	|no
node05	|no
node06	|no
node07	|no
node08	|no
node09	|no
node10	|no
node11	|no
node12	|no
node13	|no
node14	|no
node15	|**yes**
node16	|no
node17	|**yes**
node18	|no
node19	|no
node20	|no
node21	|no
node22	|no
node23	|no
node24	|no
node25	|no
node26	|**yes**
node27	|no
node28	|no
node29	|**yes**
node30	|**yes**
node31	|**yes**
node32	|no

**Comment by vpedabal** [comment]
Does reducing the sample rate help alleviate the issue?

**Comment by forzaclaudio** [comment]
Removed the release blocker because this issue was related to #90 and guidelines were provided to minimize lag in the writing of data to the DB. Even under a highly stressed network and NFS file system, this condition is expected to be transitory and therefore data is expected to be eventually written to the DB. The only condition for the above to be true is that the aggregator never goes down during the stress period, as doing so, it would cause all data in RAM memory to get lost.

**Comment by forzaclaudio** [comment]
Closing it because with the new DB schema and when using the postgres plugin in version v0.9 the issue is not present up to 13 nodes (1 AG + 12 CN)
